# addon.ftl — English (US) translations for the UFC-ABNT plugin

# --- Preferences ---
pref-title = UFC-ABNT — Preferences
pref-postprocess-title = Reference post-processing
pref-postprocess-enable = Enable automatic corrections
pref-postprocess-description =
    Applies adjustments to references generated by the CSL that cannot be
    expressed natively in the CSL format (e.g., subtitle outside bold,
    en-dash to hyphen conversion in page ranges).

# --- Startup ---
startup-csl-installed = UFC-ABNT style successfully installed.
startup-csl-updated = UFC-ABNT style updated to version { $version }.
startup-csl-already-current = UFC-ABNT style is already up to date.
