// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-postprocess-description'
  | 'pref-postprocess-enable'
  | 'pref-postprocess-title'
  | 'pref-title'
  | 'startup-csl-already-current'
  | 'startup-csl-installed'
  | 'startup-csl-updated';
