// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'format-no-changes'
  | 'format-no-items'
  | 'format-skipped-no-author'
  | 'format-success'
  | 'format-success-container'
  | 'format-success-title'
  | 'menuitem-format-title'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
